
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
message:
  data: hi there .. message from git props
  
spring:
  data:
    cassandra:
      keyspace-name: customer_keyspace 
      contact-points: localhost
      port: 9042
      schema-action: create_if_not_exists
