
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    cassandra:
      keyspace-name: customer_keyspace 
      contact-points: localhost
      port: 9042
      schema-action: none
